# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(850, 800)
        MainWindow.setStyleSheet("background-color:rgb(93,42,66);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top = QtWidgets.QWidget(self.centralwidget)
        self.top.setObjectName("top")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.top)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.menu = QtWidgets.QWidget(self.top)
        self.menu.setMaximumSize(QtCore.QSize(270, 16777215))
        self.menu.setStyleSheet("background-color:rgb(242,156,163);")
        self.menu.setObjectName("menu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.menu)
        self.verticalLayout_2.setContentsMargins(9, 0, 9, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tim_kiem = QtWidgets.QWidget(self.menu)
        self.tim_kiem.setMaximumSize(QtCore.QSize(16777215, 50))
        self.tim_kiem.setStyleSheet("")
        self.tim_kiem.setObjectName("tim_kiem")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tim_kiem)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.o_tim_kiem = QtWidgets.QLineEdit(self.tim_kiem)
        self.o_tim_kiem.setMinimumSize(QtCore.QSize(0, 30))
        self.o_tim_kiem.setStyleSheet("QLineEdit{\n"
"    border: 2px soild rgb(170, 0, 255);\n"
"    border-radius: 10px;\n"
"    color:rgb(255, 255, 255);\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"    background-color: rgba(0, 0, 0, 70);\n"
"}")
        self.o_tim_kiem.setText("")
        self.o_tim_kiem.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.o_tim_kiem.setObjectName("o_tim_kiem")
        self.horizontalLayout_2.addWidget(self.o_tim_kiem)
        self.nut_enter = QtWidgets.QPushButton(self.tim_kiem)
        self.nut_enter.setMinimumSize(QtCore.QSize(30, 30))
        self.nut_enter.setMaximumSize(QtCore.QSize(30, 30))
        self.nut_enter.setStyleSheet("QPushButton{\n"
"    background-color:rgba(0, 0, 0, 0);\n"
"    border-radius: 7px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgba(0, 0, 0, 50);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgba(0, 0, 0,70);\n"
"}")
        self.nut_enter.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/feather/filter.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nut_enter.setIcon(icon)
        self.nut_enter.setObjectName("nut_enter")
        self.horizontalLayout_2.addWidget(self.nut_enter)
        self.verticalLayout_2.addWidget(self.tim_kiem)
        self.cac_nut_bam = QtWidgets.QWidget(self.menu)
        self.cac_nut_bam.setObjectName("cac_nut_bam")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.cac_nut_bam)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.nhac_cua_toi = QtWidgets.QPushButton(self.cac_nut_bam)
        self.nhac_cua_toi.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.nhac_cua_toi.setFont(font)
        self.nhac_cua_toi.setStyleSheet("QPushButton{\n"
"    background-color: rgb(112,194,180);\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(75, 130, 120);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(54, 94, 87);\n"
"}\n"
"QPushButton:disabled {\n"
"background-color:#ff0000;\n"
"}")
        self.nhac_cua_toi.setCheckable(False)
        self.nhac_cua_toi.setChecked(False)
        self.nhac_cua_toi.setObjectName("nhac_cua_toi")
        self.verticalLayout_3.addWidget(self.nhac_cua_toi)
        self.danh_sach_phat = QtWidgets.QPushButton(self.cac_nut_bam)
        self.danh_sach_phat.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.danh_sach_phat.setFont(font)
        self.danh_sach_phat.setStyleSheet("QPushButton{\n"
"    background-color: rgb(112,194,180);\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(75, 130, 120);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(54, 94, 87);\n"
"}")
        self.danh_sach_phat.setObjectName("danh_sach_phat")
        self.verticalLayout_3.addWidget(self.danh_sach_phat)
        self.de_xuat_ngay = QtWidgets.QPushButton(self.cac_nut_bam)
        self.de_xuat_ngay.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.de_xuat_ngay.setFont(font)
        self.de_xuat_ngay.setStyleSheet("QPushButton{\n"
"    background-color: rgb(112,194,180);\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(75, 130, 120);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(54, 94, 87);\n"
"}")
        self.de_xuat_ngay.setObjectName("de_xuat_ngay")
        self.verticalLayout_3.addWidget(self.de_xuat_ngay)
        self.verticalLayout_2.addWidget(self.cac_nut_bam, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout.addWidget(self.menu)
        self.cac_page = QtWidgets.QWidget(self.top)
        self.cac_page.setMinimumSize(QtCore.QSize(600, 600))
        self.cac_page.setObjectName("cac_page")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.cac_page)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget = QtWidgets.QWidget(self.cac_page)
        self.widget.setMinimumSize(QtCore.QSize(0, 200))
        self.widget.setObjectName("widget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.box_tab_hien_thoi = QtWidgets.QWidget(self.widget)
        self.box_tab_hien_thoi.setMinimumSize(QtCore.QSize(0, 60))
        self.box_tab_hien_thoi.setMaximumSize(QtCore.QSize(16777215, 60))
        self.box_tab_hien_thoi.setObjectName("box_tab_hien_thoi")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.box_tab_hien_thoi)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.tab_hien_thoi = QtWidgets.QWidget(self.box_tab_hien_thoi)
        self.tab_hien_thoi.setMinimumSize(QtCore.QSize(250, 50))
        self.tab_hien_thoi.setMaximumSize(QtCore.QSize(250, 50))
        self.tab_hien_thoi.setStyleSheet("background-color:rgb(112,194,180);\n"
"border-radius: 10px;")
        self.tab_hien_thoi.setObjectName("tab_hien_thoi")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab_hien_thoi)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label = QtWidgets.QLabel(self.tab_hien_thoi)
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_9.addWidget(self.label)
        self.verticalLayout_8.addWidget(self.tab_hien_thoi, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.verticalLayout_7.addWidget(self.box_tab_hien_thoi, 0, QtCore.Qt.AlignLeft)
        self.change_file = QtWidgets.QWidget(self.widget)
        self.change_file.setMinimumSize(QtCore.QSize(0, 60))
        self.change_file.setMaximumSize(QtCore.QSize(16777215, 60))
        self.change_file.setObjectName("change_file")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.change_file)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.add_file = QtWidgets.QPushButton(self.change_file)
        self.add_file.setMinimumSize(QtCore.QSize(170, 50))
        self.add_file.setMaximumSize(QtCore.QSize(170, 50))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.add_file.setFont(font)
        self.add_file.setStyleSheet("QPushButton{\n"
"    background-color: rgb(112,194,180);\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(75, 130, 120);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(54, 94, 87);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/feather/file.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_file.setIcon(icon1)
        self.add_file.setIconSize(QtCore.QSize(20, 20))
        self.add_file.setObjectName("add_file")
        self.horizontalLayout_3.addWidget(self.add_file)
        self.pushButton = QtWidgets.QPushButton(self.change_file)
        self.pushButton.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    background-color: rgb(112,194,180);\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(75, 130, 120);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(54, 94, 87);\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/feather/folder-plus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon2)
        self.pushButton.setIconSize(QtCore.QSize(20, 20))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.delete_file = QtWidgets.QPushButton(self.change_file)
        self.delete_file.setMinimumSize(QtCore.QSize(170, 50))
        self.delete_file.setMaximumSize(QtCore.QSize(170, 50))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.delete_file.setFont(font)
        self.delete_file.setStyleSheet("QPushButton{\n"
"    background-color: rgb(112,194,180);\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(75, 130, 120);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(54, 94, 87);\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/feather/trash-2.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_file.setIcon(icon3)
        self.delete_file.setIconSize(QtCore.QSize(20, 20))
        self.delete_file.setObjectName("delete_file")
        self.horizontalLayout_3.addWidget(self.delete_file)
        self.verticalLayout_7.addWidget(self.change_file)
        self.verticalLayout_6.addWidget(self.widget)
        self.danh_sach_bai_hat = QtWidgets.QTableWidget(self.cac_page)
        self.danh_sach_bai_hat.setStyleSheet("border: null;")
        self.danh_sach_bai_hat.setObjectName("danh_sach_bai_hat")
        self.danh_sach_bai_hat.setColumnCount(0)
        self.danh_sach_bai_hat.setRowCount(0)
        self.verticalLayout_6.addWidget(self.danh_sach_bai_hat)
        self.horizontalLayout.addWidget(self.cac_page)
        self.verticalLayout.addWidget(self.top)
        self.bot = QtWidgets.QWidget(self.centralwidget)
        self.bot.setMinimumSize(QtCore.QSize(0, 120))
        self.bot.setMaximumSize(QtCore.QSize(16777215, 120))
        self.bot.setStyleSheet("background-color: rgb(247,202,205);")
        self.bot.setObjectName("bot")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.bot)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.bar_and_time = QtWidgets.QWidget(self.bot)
        self.bar_and_time.setMinimumSize(QtCore.QSize(0, 50))
        self.bar_and_time.setMaximumSize(QtCore.QSize(16777215, 50))
        self.bar_and_time.setObjectName("bar_and_time")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.bar_and_time)
        self.horizontalLayout_4.setContentsMargins(-1, 9, -1, -1)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.thoi_gian_troi_qua = QtWidgets.QLabel(self.bar_and_time)
        self.thoi_gian_troi_qua.setMinimumSize(QtCore.QSize(50, 30))
        self.thoi_gian_troi_qua.setMaximumSize(QtCore.QSize(50, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.thoi_gian_troi_qua.setFont(font)
        self.thoi_gian_troi_qua.setObjectName("thoi_gian_troi_qua")
        self.horizontalLayout_4.addWidget(self.thoi_gian_troi_qua, 0, QtCore.Qt.AlignLeft)
        self.load_bar = QtWidgets.QSlider(self.bar_and_time)
        self.load_bar.setMinimumSize(QtCore.QSize(0, 30))
        self.load_bar.setMaximumSize(QtCore.QSize(16777215, 30))
        self.load_bar.setStyleSheet("QSlider::groove:horizontal {\n"
"    border: none;\n"
"    height: 7px;\n"
"    background: #C0C0C0;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background:rgb(202, 132, 81);\n"
"    border: none;\n"
"    width: 7px;\n"
"    height: 7px;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"    background: rgb(255, 255, 255);\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"    background: rgb(0, 0, 0);\n"
"    border-radius: 3px;\n"
"}")
        self.load_bar.setOrientation(QtCore.Qt.Horizontal)
        self.load_bar.setObjectName("load_bar")
        self.horizontalLayout_4.addWidget(self.load_bar)
        self.thoi_gian_con_lai = QtWidgets.QLabel(self.bar_and_time)
        self.thoi_gian_con_lai.setMinimumSize(QtCore.QSize(50, 30))
        self.thoi_gian_con_lai.setMaximumSize(QtCore.QSize(50, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.thoi_gian_con_lai.setFont(font)
        self.thoi_gian_con_lai.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.thoi_gian_con_lai.setObjectName("thoi_gian_con_lai")
        self.horizontalLayout_4.addWidget(self.thoi_gian_con_lai, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_4.addWidget(self.bar_and_time)
        self.bottom = QtWidgets.QWidget(self.bot)
        self.bottom.setMinimumSize(QtCore.QSize(0, 70))
        self.bottom.setMaximumSize(QtCore.QSize(16777215, 70))
        self.bottom.setObjectName("bottom")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.bottom)
        self.horizontalLayout_5.setContentsMargins(9, 0, 9, 10)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.dang_nghe = QtWidgets.QWidget(self.bottom)
        self.dang_nghe.setMinimumSize(QtCore.QSize(250, 0))
        self.dang_nghe.setObjectName("dang_nghe")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.dang_nghe)
        self.verticalLayout_5.setContentsMargins(9, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.text_dang_nghe = QtWidgets.QLabel(self.dang_nghe)
        self.text_dang_nghe.setMinimumSize(QtCore.QSize(0, 0))
        self.text_dang_nghe.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.text_dang_nghe.setFont(font)
        self.text_dang_nghe.setStyleSheet("")
        self.text_dang_nghe.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.text_dang_nghe.setFrameShadow(QtWidgets.QFrame.Plain)
        self.text_dang_nghe.setLineWidth(1)
        self.text_dang_nghe.setObjectName("text_dang_nghe")
        self.verticalLayout_5.addWidget(self.text_dang_nghe)
        self.horizontalLayout_5.addWidget(self.dang_nghe)
        self.dieu_khien = QtWidgets.QWidget(self.bottom)
        self.dieu_khien.setMinimumSize(QtCore.QSize(330, 50))
        self.dieu_khien.setMaximumSize(QtCore.QSize(16777215, 50))
        self.dieu_khien.setStyleSheet("")
        self.dieu_khien.setObjectName("dieu_khien")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.dieu_khien)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.nghe_lai = QtWidgets.QPushButton(self.dieu_khien)
        self.nghe_lai.setMinimumSize(QtCore.QSize(30, 30))
        self.nghe_lai.setMaximumSize(QtCore.QSize(30, 30))
        self.nghe_lai.setStyleSheet("QPushButton{\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    border-radius: 8px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgba(0, 0, 0,40);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgba(0, 0, 0,70);\n"
"}")
        self.nghe_lai.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/feather/repeat.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nghe_lai.setIcon(icon4)
        self.nghe_lai.setObjectName("nghe_lai")
        self.horizontalLayout_6.addWidget(self.nghe_lai)
        self.prev = QtWidgets.QPushButton(self.dieu_khien)
        self.prev.setMinimumSize(QtCore.QSize(50, 50))
        self.prev.setMaximumSize(QtCore.QSize(50, 50))
        self.prev.setStyleSheet("QPushButton{\n"
"    background-color:rgba(0, 0, 0, 0);\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgba(0, 0, 0,40);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgba(0, 0, 0,70);\n"
"}")
        self.prev.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/newPrefix/feather/skip-back.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.prev.setIcon(icon5)
        self.prev.setIconSize(QtCore.QSize(16, 16))
        self.prev.setObjectName("prev")
        self.horizontalLayout_6.addWidget(self.prev)
        self.pause = QtWidgets.QPushButton(self.dieu_khien)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pause.sizePolicy().hasHeightForWidth())
        self.pause.setSizePolicy(sizePolicy)
        self.pause.setMinimumSize(QtCore.QSize(50, 50))
        self.pause.setMaximumSize(QtCore.QSize(50, 50))
        self.pause.setSizeIncrement(QtCore.QSize(0, 0))
        self.pause.setBaseSize(QtCore.QSize(0, 0))
        self.pause.setStyleSheet("QPushButton{\n"
"    background-color:rgba(0, 0, 0, 0);\n"
"    border-radius: 40px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgba(0, 0, 0,40);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgba(0, 0, 0,70);\n"
"}")
        self.pause.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/newPrefix/feather/pause-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap(":/newPrefix/feather/play-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon6.addPixmap(QtGui.QPixmap(":/newPrefix/feather/pause-circle.svg"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap(":/newPrefix/feather/play-circle.svg"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        icon6.addPixmap(QtGui.QPixmap(":/newPrefix/feather/pause-circle.svg"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap(":/newPrefix/feather/play-circle.svg"), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon6.addPixmap(QtGui.QPixmap(":/newPrefix/feather/pause-circle.svg"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap(":/newPrefix/feather/play-circle.svg"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.pause.setIcon(icon6)
        self.pause.setIconSize(QtCore.QSize(30, 30))
        self.pause.setCheckable(True)
        self.pause.setChecked(False)
        self.pause.setAutoDefault(False)
        self.pause.setDefault(False)
        self.pause.setFlat(False)
        self.pause.setObjectName("pause")
        self.horizontalLayout_6.addWidget(self.pause)
        self.next = QtWidgets.QPushButton(self.dieu_khien)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(50)
        sizePolicy.setHeightForWidth(self.next.sizePolicy().hasHeightForWidth())
        self.next.setSizePolicy(sizePolicy)
        self.next.setMinimumSize(QtCore.QSize(50, 50))
        self.next.setMaximumSize(QtCore.QSize(50, 50))
        self.next.setStyleSheet("QPushButton{\n"
"    background-color:rgba(0, 0, 0, 0);\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgba(0, 0, 0,40);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgba(0, 0, 0,70);\n"
"}")
        self.next.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/newPrefix/feather/skip-forward.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.next.setIcon(icon7)
        self.next.setIconSize(QtCore.QSize(16, 16))
        self.next.setCheckable(False)
        self.next.setChecked(False)
        self.next.setObjectName("next")
        self.horizontalLayout_6.addWidget(self.next)
        self.loa = QtWidgets.QPushButton(self.dieu_khien)
        self.loa.setMinimumSize(QtCore.QSize(30, 30))
        self.loa.setMaximumSize(QtCore.QSize(30, 30))
        self.loa.setStyleSheet("QPushButton{\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    border-radius: 8px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgba(0, 0, 0,40);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgba(0, 0, 0,70);\n"
"}")
        self.loa.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/newPrefix/feather/volume-2.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon8.addPixmap(QtGui.QPixmap(":/newPrefix/feather/volume-x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon8.addPixmap(QtGui.QPixmap(":/newPrefix/feather/volume-2.svg"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon8.addPixmap(QtGui.QPixmap(":/newPrefix/feather/volume-x.svg"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        icon8.addPixmap(QtGui.QPixmap(":/newPrefix/feather/volume-2.svg"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon8.addPixmap(QtGui.QPixmap(":/newPrefix/feather/volume-x.svg"), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon8.addPixmap(QtGui.QPixmap(":/newPrefix/feather/volume-2.svg"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon8.addPixmap(QtGui.QPixmap(":/newPrefix/feather/volume-x.svg"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.loa.setIcon(icon8)
        self.loa.setCheckable(True)
        self.loa.setObjectName("loa")
        self.horizontalLayout_6.addWidget(self.loa)
        self.horizontalLayout_5.addWidget(self.dieu_khien)
        self.am_luong_and_nghe_lai = QtWidgets.QWidget(self.bottom)
        self.am_luong_and_nghe_lai.setMinimumSize(QtCore.QSize(250, 0))
        self.am_luong_and_nghe_lai.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.am_luong_and_nghe_lai.setObjectName("am_luong_and_nghe_lai")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.am_luong_and_nghe_lai)
        self.horizontalLayout_7.setContentsMargins(0, 0, 9, 0)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_2 = QtWidgets.QPushButton(self.am_luong_and_nghe_lai)
        self.pushButton_2.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_2.setStyleSheet("background-color:rgba(255, 255, 255, 0);")
        self.pushButton_2.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/newPrefix/feather/volume-2.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon9)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_7.addWidget(self.pushButton_2)
        self.volume = QtWidgets.QSlider(self.am_luong_and_nghe_lai)
        self.volume.setMinimumSize(QtCore.QSize(150, 0))
        self.volume.setMaximumSize(QtCore.QSize(150, 16777215))
        self.volume.setStyleSheet("QSlider::groove:horizontal {\n"
"    border: none;\n"
"    height: 7px;\n"
"    background: #C0C0C0;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background:rgb(202, 132, 81);\n"
"    border: none;\n"
"    width: 7px;\n"
"    height: 7px;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"    background: rgb(255, 255, 255);\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"    background: rgb(0, 0, 0);\n"
"    border-radius: 3px;\n"
"}")
        self.volume.setOrientation(QtCore.Qt.Horizontal)
        self.volume.setObjectName("volume")
        self.horizontalLayout_7.addWidget(self.volume)
        self.horizontalLayout_5.addWidget(self.am_luong_and_nghe_lai, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_4.addWidget(self.bottom)
        self.verticalLayout.addWidget(self.bot)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.o_tim_kiem.setPlaceholderText(_translate("MainWindow", "Search"))
        self.nhac_cua_toi.setText(_translate("MainWindow", "My Music"))
        self.danh_sach_phat.setText(_translate("MainWindow", "PlayList"))
        self.de_xuat_ngay.setText(_translate("MainWindow", "Daily Suggest"))
        self.label.setText(_translate("MainWindow", "TAB HIEN THOI"))
        self.add_file.setText(_translate("MainWindow", "ADD FILE"))
        self.pushButton.setText(_translate("MainWindow", "ADD FOLDER"))
        self.delete_file.setText(_translate("MainWindow", "DELETE"))
        self.thoi_gian_troi_qua.setText(_translate("MainWindow", "01:30"))
        self.thoi_gian_con_lai.setText(_translate("MainWindow", "01:30"))
        self.text_dang_nghe.setText(_translate("MainWindow", "Now: Dusk Till Dawn"))
import icon_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
